// rubs
export const ADD_RUBRIQUE = 'ADD_RUBRIQUE'
export const EDIT_RUBRIQUE = 'EDIT_RUBRIQUE'
export const DELETE_RUBRIQUE = 'DELETE_RUBRIQUE'
export const CANCEL_EDIT_RUBRIQUE = 'CANCEL_EDIT_RUBRIQUE'
export const SUBMIT_RUBRIQUE = 'SUBMIT_RUBRIQUE'
export const RECEIVE_RUBRIQUES = 'RECEIVE_RUBRIQUES'

// auth
export const AUTHENTICATE = 'AUTHENTICATE'
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE'

// dashboard
export const RECEIVE_HUBS = 'RECEIVE_HUBS'